version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: database
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      JWT_SECRET: mysecret
    depends_on:
      - database
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
