name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          cd ../backend  
          npm ci

      - name: Run frontend tests
        run: |
          cd frontend
          npm run test

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Build backend
        run: |
          cd backend
          npm run build

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build

      - name: Upload backend build artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: backend/dist

  build-docker-images:
    needs: build-and-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download frontend build artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: frontend/build

      - name: Download backend build artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-build
          path: backend/dist

      - name: Build frontend image
        run: |
          cd frontend
          docker build -t myapp-frontend .

      - name: Build backend image
        run: |
          cd backend
          docker build -t myapp-backend .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push frontend image
        run: |
          docker tag myapp-frontend ${{ secrets.DOCKERHUB_USERNAME }}/myapp-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp-frontend:${{ github.sha }}

      - name: Push backend image
        run: |
          docker tag myapp-backend ${{ secrets.DOCKERHUB_USERNAME }}/myapp-backend:${{ github.sha }}  
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp-backend:${{ github.sha }}
