name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: student_community
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Database Schema
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u root -proot_password student_community < backend/config/init.sql

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Start Backend Server
        run: |
          cd backend
          npm start &
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root_password
          DB_NAME: student_community
          JWT_SECRET: your_jwt_secret

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Start Frontend Server
        run: |
          cd frontend
          npm start &
        env:
          REACT_APP_API_URL: http://localhost:5000

      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install

      - name: Run Frontend EndToEnd Tests
        run: |
          cd frontend
          npm run test:e2e

      - name: Build Frontend
        run: |
          cd frontend
          npm run build
