name: EndToEnd Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: student_community
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Wait for MySQL to be ready
        run: |
          timeout 60s bash -c 'until mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do sleep 1; done'

      - name: Check MySQL user
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.DB_PASSWORD }} -e "SELECT User, Host, plugin FROM mysql.user;"

      - name: Set up Database Schema
        run: |
          echo "Initializing database schema..."
          mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.DB_PASSWORD }} student_community < backend/init_db.sql
          echo "Database schema initialized"

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm ci

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm ci

      - name: Install Playwright
        run: |
          cd frontend
          npx playwright install --with-deps

      - name: Start Backend Server
        run: |
          cd backend
          npm start &
        env:
          DB_HOST: localhost
          DB_USER: root
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: student_community
          JWT_SECRET: your_jwt_secret

      - name: Wait for Backend Server
        run: |
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:5000/api/health)" != "200" ]]; do sleep 5; done' || false

      - name: Start Frontend Server
        run: |
          cd frontend
          npm start &
        env:
          REACT_APP_API_URL: http://localhost:5000/api

      - name: Wait for Frontend Server
        run: |
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 5; done' || false

      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright test
        env:
          CI: true
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:3000
          TEST_USER_USERNAME: ${{ secrets.TEST_USER_USERNAME }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: your_jwt_secret

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: playwright-screenshots
          path: frontend/test-results/
          retention-days: 30
