name: EndToEnd Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: student_community
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm ci

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm ci

      - name: Install Playwright
        run: |
          cd frontend
          npx playwright install --with-deps

      - name: Start Backend Server
        run: |
          cd backend
          npm start &
        env:
          DB_HOST: localhost
          DB_USER: root
          DB_PASSWORD: root_password
          DB_NAME: student_community
          JWT_SECRET: your_jwt_secret

      - name: Wait for Backend Server
        run: |
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:5000/api/health)" != "200" ]]; do sleep 5; done' || false

      - name: Start Frontend Server
        run: |
          cd frontend
          npm start &
        env:
          REACT_APP_API_URL: http://localhost:5000/api

      - name: Wait for Frontend Server
        run: |
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 5; done' || false

      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright test
        env:
          CI: true
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:3000

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: playwright-screenshots
          path: frontend/test-results/
          retention-days: 30
